# Generated by Django 3.2.15 on 2022-10-17 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort', '0003_alter_ski_data_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ski',
            name='data_today',
            field=models.DateField(default=datetime.datetime(3022, 10, 17, 12, 10, 14, 787984), verbose_name='Сегодняшний день'),
        ),
    ]
