# Generated by Django 3.2.15 on 2022-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_next_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_level',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Очков на уровне'),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_level',
            field=models.IntegerField(blank=True, default=1000, null=True, verbose_name='Очков для следущего уровня'),
        ),
    ]
